# Generated by Django 6.0.2 on 2026-02-26 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('organization', models.CharField(default='Global', max_length=100)),
                ('domain', models.CharField(default='General', max_length=100)),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Internship', 'Internship'), ('Research', 'Research'), ('Conference', 'Conference'), ('General', 'General')], default='General', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('hackathons', models.IntegerField(default=0)),
                ('internships', models.IntegerField(default=0)),
                ('research_papers', models.IntegerField(default=0)),
                ('coding_rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
