# Generated by Django 5.2.11 on 2026-02-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('Internship', 'Internship'), ('Research', 'Research'), ('Conference', 'Conference'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
